apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiservice.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- rolebinding.yaml
- service.yaml
- serviceaccount.yaml
