apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- customresourcedefinition.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
namespace: connect
