apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/v0.0.33
patches:
  - path: patches/patch-configmap.yaml
  - path: patches/patch-namespace.yaml
  - path: patches/patch-storageclass.yaml
