apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-namespace.yaml
- certificate.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- customresourcedefinition.yaml
- deployment.yaml
- issuer.yaml
- mutatingwebhookconfiguration.yaml
- pod.yaml
- role.yaml
- rolebinding.yaml
- service.yaml
- serviceaccount.yaml
- validatingwebhookconfiguration.yaml
