# Source: connect/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onepassword-connect-operator
  namespace: connect
  labels:
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: connect
    app.kubernetes.io/version: "1.8.1"
