# Source: connect/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onepassword-connect-operator
  labels:
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: connect
    app.kubernetes.io/version: "1.8.1"
subjects:
- kind: ServiceAccount
  name: onepassword-connect-operator
  namespace: connect
roleRef:
  kind: ClusterRole
  name: onepassword-connect-operator
  apiGroup: rbac.authorization.k8s.io
