apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- deployment.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml
- storageclass.yaml
namespace: local-path-storage
