apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../manifests/argocd/components/v3.0.5
- patches/argocd-auth.yaml
- http_route.yaml
- http_redirect.yaml

patches:
- path: patches/argocd-cm.yaml
- path: patches/argocd-rbac-cm.yaml
- path: patches/argocd-cmd-params-cm.yaml
