# Source: connect/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: connect
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: connect
    app.kubernetes.io/version: "1.7.3"
spec:
  type: NodePort
  selector:
    app: onepassword-connect
  ports:
    - port: 8081
      name: connect-sync
    - port: 8080
      name: connect-api
