apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-cephfs-ctrlplugin-sa
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
  annotations:
    {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-cephfs-nodeplugin-sa
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
  annotations:
    {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-controller-manager
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
  annotations:
    {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-nfs-ctrlplugin-sa
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
  annotations:
    {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-nfs-nodeplugin-sa
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
  annotations:
    {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-rbd-ctrlplugin-sa
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
  annotations:
    {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-rbd-nodeplugin-sa
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
  annotations:
    {}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph # namespace:cluster
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph # namespace:cluster
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-cmd-reporter
  namespace: rook-ceph # namespace:cluster
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-purge-osd
  namespace: rook-ceph # namespace:cluster
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-rgw
  namespace: rook-ceph # namespace:cluster
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-default
  namespace: rook-ceph # namespace:cluster
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-system
  namespace: rook-ceph # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-cephfs-plugin-sa
  namespace: rook-ceph # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-cephfs-provisioner-sa
  namespace: rook-ceph # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-rbd-plugin-sa
  namespace: rook-ceph # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-rbd-provisioner-sa
  namespace: rook-ceph # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.9
    app.kubernetes.io/part-of: rook-ceph-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: objectstorage-provisioner
  namespace: rook-ceph # namespace:operator
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/name: cosi-driver-ceph
